### ISSUE TITLE
Mongo DB connection error

### ISSUE THREAD

**Issue by Sakshidiwedi-28** [Sakshidiwedi-28/Doctor-Appointment-System#2] opened 2024-11-22 07:49 UTC
![image](https://github.com/user-attachments/assets/e6797453-0272-48e4-834f-fdd6e05b47da)

The current `npm run dev` shows this error in the terminal. Kindly work on this by sharing your approach to what the error is and how you are going to resolve this error.

**Comment by monish-j** [comment] 2024-11-22 12:33
Hi Sakshi,

I noticed you have an  issue regarding the MongoDB connection error in your project. I’d like to help you resolve these issues and contribute to your project. Would you like me to assist?

Best regards, monish-j

**Comment by monish-j** [comment] 2024-11-22 14:37
Hi Sakshi,

I’ve identified and fixed the MongoDB connection error in your project. I’ve created a pull request with the necessary changes. Please review and merge the pull request to resolve the issue.


Here’s a screenshot of the terminal after running npm run dev successfully (note: the key is hidden for security):

![mongo screenshot](https://github.com/user-attachments/assets/adb365cb-9820-47c4-9d01-061cc72b90cc)

Best regards,
monish-j

**Comment by monish-j** [comment] 2024-11-22 15:21
Hi Sakshi,

I noticed that you encountered an error: EADDRINUSE: address already in use :::8080. This error occurs when the port 8080 is already being used by another process. Here’s my approach to resolving this error:

**Reason for the Error**

The error **EADDRINUSE: address already in use :::8080** indicates that port 8080 is already occupied by another application or another instance of the same application. This can happen if:

- Another instance of your server is already running.

- Another application is using port 8080.

**Steps to Resolve the Error**

**1. Identify the Process Using the Port:**

On Windows, you can use the following command to find the process ID (PID) using port 8080:

**bash**
netstat -ano | findstr :8080

- This will display the PID of the process using port 8080.

**2. Terminate the Process:**

Once you have the PID, you can terminate the process using the following command:

**bash**
taskkill /PID <PID> /F

- Replace PID with the actual process ID.

**3. Change the Port Number:**

If terminating the process is not an option, you can change the port number in your .env file or in your server configuration file to use a different port, such as 8081:

PORT=8081

**4. Restart the Server:**

- After making these changes, restart your server to see if the issue is resolved.

**Additional Information**
 I am using MongoDB Atlas, a cloud-based solution, which might be different from your local MongoDB setup. If you are using a local MongoDB instance, these steps should help resolve the port conflict.

By following these steps, you should be able to resolve the EADDRINUSE error and get your server running smoothly. If you encounter any further issues, feel free to reach out!

Best regards, monish-j

**Closed as completed** 2024-12-03 09:13 UTC
Labels: enhancement, good first issue
